config/routes.rb
Rails.application.routes.draw do

  resources :replacement_parameters
  
  resources :changes

  root 'replacement_parameters#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aviacompany.rb
class Aviacompany < ApplicationRecord
  validates :title, presence: true

  has_one :replacement_parameter
  has_one :change
end

app/models/change.rb
class Change < ApplicationRecord
  belongs_to :aviacompany, optional: true

  def change_email!
    
    self.email.gsub!(/[@]/, self.aviacompany.replacement_parameter.email)
    self.save!
  end

  def change_phone!
    self.phone.gsub!(/^../, self.aviacompany.replacement_parameter.phone) 
    self.save!   
  end
end

app/models/email.rb
class Email < ApplicationRecord
end

app/models/pasport.rb
class Pasport < ApplicationRecord
end

app/models/phone.rb
class Phone < ApplicationRecord
end

app/models/replacement_parameter.rb
class ReplacementParameter < ApplicationRecord
  belongs_to :aviacompany, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/changes_controller.rb
class ChangesController < ApplicationController
  
  def show
    @change = Change.find(params[:id])
  end

  def new
    @change = Change.new
  end

  def create
    @change = Change.new(change_params)
    @change.save
    @change.change_email!
    @change.change_phone!
    redirect_to @change
  end

  private

  def change_params
    params.require(:change).permit(:aviacompany_id, :email, :phone, :pasport)
  end
end

app/controllers/replacement_parameters_controller.rb
class ReplacementParametersController < ApplicationController
  
  def index

  end

  def new
    @replacement_parameter = ReplacementParameter.new
  end

  def create
    @replacement_parameter = ReplacementParameter.new(replacement_parameter_params)
    @replacement_parameter.save
  end


  private

  def replacement_parameter_params
    params.require(:replacement_parameter).permit(:aviacompany_id, :email, :phone, :pasport)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/changes_helper.rb
module ChangesHelper
end

app/helpers/replacement_parameters_helper.rb
module ReplacementParametersHelper
end

app/helpers/user_datas_helper.rb
module UserDatasHelper
end

app/views/changes/new.html.slim
h1
  | New Data тут мы вводим почту и телефон, которые будут изменены, чтобы проверить работу методов

= form_with model: @change, local: true do |form|
  
  p
    = form.label :aviacompany_id
    = form.collection_select :aviacompany_id, Aviacompany.all, :id, :title, prompt: true

  p
    = form.label :email
    = form.text_field :email, id: :change_email  

  p
    = form.label :phone
    = form.text_field :phone, id: :change_phone 

  p
    = form.label :pasport
    = form.text_field :pasport, id: :change_pasport    
  
  p
    = form.submit 

app/views/changes/show.html.slim
p= @change.email

p= @change.phone

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aviatickets</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/replacement_parameters/new.html.slim
h1
  | New Parameter Тут выбираем авиакомпанию и задаем параментры замены

= form_with model: @replacement_parameter, local: true do |form|
  
  p
    = form.label :aviacompany_id
    = form.collection_select :aviacompany_id, Aviacompany.all, :id, :title, prompt: true

  p
    = form.label :email
    = form.collection_select :email, Email.all, :mail, :mail, prompt: true  

  p
    = form.label :phone
    = form.collection_select :phone, Phone.all, :phone, :phone, prompt: true 

  p
    = form.label :pasport
    = form.collection_select :pasport, Pasport.all, :pasport, :pasport, prompt: true    
  
  p
    = form.submit 

= link_to 'Change user data', new_change_path